import "./globals.css";
import type { Metadata } from "next";
import type { ChildrenNode } from "@/types/ChildrenNode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenNode) {
  return (
    <html lang="en">
      <body className="dark">{children}</body>
    </html>
  );
}
