import "./globals.css";
import type { Metadata } from "next";
import type { ChildrenNode } from "@/types/ChildrenNode";

import { Inter } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenNode) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark relative min-h-screen max-w-screen`}>
        <Navbar />
        <main className="h-full w-[95%] max-w-7xl py-30 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
